### ISSUE TITLE
Holes missing

### ISSUE THREAD

**Issue by ARKopp** [vonkonow/LEET-Synthesizer#3]
Can you put all the holes for the arduino in.

Now you have to clip of some legs

**Comment by vonkonow** [comment]
Hi 
The idea is to use a pro micro _without_ pin header. I have deliberately not added holes to make it easier to see if any wires are missing. Please also note that there are wires routed under some of the pins, so there is a risk of short circuit if pins are kept…
I recommend to de-solder the pin header, but you can try to drill holes if needed (a tip: make a small dimple with the soldering iron first).
